import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import { useTheme } from "../hooks/useTheme";
import { theme } from "../chakra";
import Header from "../components/Header";
import Head from "next/head";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

const client = new ApolloClient({
  uri: "https://analytics-api.herokuapp.com/analytics",
  cache: new InMemoryCache(),
});
function MyApp({ Component, pageProps }: AppProps) {
  const themeTools = useTheme();

  return (
    <ChakraProvider theme={theme(themeTools.currentTheme)}>
      <ColorModeScript
        initialColorMode={
          theme(themeTools.currentTheme).config.initialColorMode
        }
      />
      <Head>
        <title>ASlytics</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header {...themeTools} />
      <ApolloProvider client={client}>
        <Component {...pageProps} />
      </ApolloProvider>
    </ChakraProvider>
  );
}

export default MyApp;
